name: gha-result
on:
  push:
    branches:
    - branch-1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: '8'
    - run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true
#     # This item has no matching transformer
#     - email:
#       - a@binarywang.com
# email notification action not provided in github. but can use smtp service. refer to the report 
    - name: Send email notification
      run: echo "Email notification sent to a@binarywang.com"
