name: placeholder_Name

on:
  push:
    branches:
      - branch-2

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3.5.0
        - name: Set up cache
          uses: actions/cache@v4
          with:
            path: "${{ github.workspace }}/.m2/repository"
            key: "${{ runner.os }}-path"
        - uses: actions/setup-java@v3.12.0
          with:
            distribution: zulu
            java-version: '8'
        
 #-   name: build with maven-
    #     uses: actions/checkout@version
    #     run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

# macos:
#   jdk: openjdk8

