name: Manually Migrated Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    -  name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
      distribution: 'zulu' 
      java-version: '8'